import { SpatialZoneConfig } from './types';

export const SPATIAL_ZONES: SpatialZoneConfig[] = [
  {
    id: 'zone-cognitive',
    name: 'Cognitive Activities',
    category: 'cognitive',
    emoji: '🧠',
    color: '#19C3B1',
    accentColor: '#38D9C5',
    glowColor: 'rgba(25, 195, 177, 0.4)',
    tagline: 'Culturally Rooted Engagement',
    shortDesc: 'Adaptive memory, attention, pattern, and familiar sound exercises.',
    fullDesc: 'Interactive games incorporating Assam tea leaf sorting, Bihu dhol rhythm matching, Khasi spice recall, and Mizo textile sequences to stimulate neuroplasticity.',
    keyMetric: '6 Cognitive Domains',
    targetSectionId: 'section-cognitive-activities',
    position: [0, 1.2, 4.0],
    orbitRadius: 4.0,
    angle: 0,
  },
  {
    id: 'zone-routine',
    name: 'Daily Routine',
    category: 'routine',
    emoji: '📅',
    color: '#F4B740',
    accentColor: '#F59E0B',
    glowColor: 'rgba(244, 183, 64, 0.4)',
    tagline: 'Predictable Circadian Structure',
    shortDesc: 'Structured daily timeline for medication, hydration, and restful pacing.',
    fullDesc: 'Paced daily schedule with morning medication photo checks, hydration tracking, midday cognitive exercise, and evening calming routines to ease sundowning.',
    keyMetric: '92% Medication Adherence',
    targetSectionId: 'section-daily-routine',
    position: [2.8, 0.8, 2.8],
    orbitRadius: 4.1,
    angle: 40,
  },
  {
    id: 'zone-memory',
    name: 'Memory Garden',
    category: 'memory',
    emoji: '🌿',
    color: '#EC4899',
    accentColor: '#F472B6',
    glowColor: 'rgba(236, 72, 153, 0.4)',
    tagline: 'Reminiscence Sanctuary',
    shortDesc: 'Digital memory blossoms preserving cherished ancestral life stories.',
    fullDesc: 'Interactive blossoms revealing family wedding photos, Kaziranga trips, and village memories accompanied by gentle family voice narrations.',
    keyMetric: '18 Animated Blossoms',
    targetSectionId: 'section-memory-garden',
    position: [4.0, 0.4, 0],
    orbitRadius: 4.0,
    angle: 80,
  },
  {
    id: 'zone-family',
    name: 'Family Connect',
    category: 'family',
    emoji: '👨‍👩‍👧',
    color: '#FF5C6C',
    accentColor: '#F87171',
    glowColor: 'rgba(255, 92, 108, 0.4)',
    tagline: 'One-Touch Togetherness',
    shortDesc: 'Instant audio messages and speed-dial to loving family members.',
    fullDesc: 'Connects elders with children living in Guwahati, Delhi, or Bengaluru with single-tap photo calling and asynchronous voice love notes.',
    keyMetric: 'Instant Voice Dispatch',
    targetSectionId: 'section-family-connect',
    position: [2.8, 0.2, -2.8],
    orbitRadius: 4.1,
    angle: 120,
  },
  {
    id: 'zone-caregiver',
    name: 'Caregiver Portal',
    category: 'caregiver',
    emoji: '👩‍⚕️',
    color: '#35D07F',
    accentColor: '#10B981',
    glowColor: 'rgba(53, 208, 127, 0.4)',
    tagline: 'Remote Peace of Mind',
    shortDesc: 'Real-time telemetry, missed dose alerts, and mood monitoring.',
    fullDesc: 'Enables family caregivers to stay connected without feeling intrusive, providing live status updates and emergency notification routing.',
    keyMetric: 'Real-Time Family Sync',
    targetSectionId: 'section-caregiver',
    position: [0, 0.6, -4.0],
    orbitRadius: 4.0,
    angle: 160,
  },
  {
    id: 'zone-clinician',
    name: 'Clinician Telemetry',
    category: 'clinician',
    emoji: '🩺',
    color: '#8B7CFF',
    accentColor: '#A78BFA',
    glowColor: 'rgba(139, 124, 255, 0.4)',
    tagline: 'Longitudinal Objective Insight',
    shortDesc: 'MoCA/MMSE aligned trajectory curves and exportable clinical reports.',
    fullDesc: 'Neurologists and medical officers track 30-day cognitive retention curves, response latency drifts, and export FHIR/ABDM compliant summaries.',
    keyMetric: 'MoCA & MMSE Mapped',
    targetSectionId: 'section-clinician',
    position: [-2.8, 0.8, -2.8],
    orbitRadius: 4.1,
    angle: 200,
  },
  {
    id: 'zone-ai',
    name: 'AI Personalization',
    category: 'ai',
    emoji: '🤖',
    color: '#5BA7FF',
    accentColor: '#60A5FA',
    glowColor: 'rgba(91, 167, 255, 0.4)',
    tagline: 'Ethical Closed-Loop DDA',
    shortDesc: 'Dynamic difficulty adaptation and circadian sundowning anticipation.',
    fullDesc: 'On-device machine learning adapts activity pacing dynamically to prevent cognitive fatigue while maintaining positive engagement.',
    keyMetric: 'Zero Frustration Engine',
    targetSectionId: 'section-ai-intelligence',
    position: [-4.0, 0.5, 0],
    orbitRadius: 4.0,
    angle: 240,
  },
  {
    id: 'zone-language',
    name: 'Languages & Dialects',
    category: 'language',
    emoji: '🌐',
    color: '#38D9C5',
    accentColor: '#2DD4BF',
    glowColor: 'rgba(56, 217, 197, 0.4)',
    tagline: 'North East Multilingual Voice',
    shortDesc: 'Native dialect voice AI speaking Assamese, Bengali, Bodo, Khasi, Meitei & Mizo.',
    fullDesc: 'Speech synthesis and acoustic analysis engineered for elder vocal cadence, dialect colloquialisms, and low-literacy senior accessibility.',
    keyMetric: '7 Regional Dialects',
    targetSectionId: 'section-voice-language',
    position: [-2.8, 1.2, 2.8],
    orbitRadius: 4.1,
    angle: 280,
  },
  {
    id: 'zone-security',
    name: 'Security & Privacy Vault',
    category: 'security',
    emoji: '🔒',
    color: '#2563EB',
    accentColor: '#3B82F6',
    glowColor: 'rgba(37, 99, 235, 0.4)',
    tagline: 'DPDP Act 2023 & AES-256',
    shortDesc: 'Encrypted on-device health data vault with zero commercial monetization.',
    fullDesc: 'Full compliance with the Indian Digital Personal Data Protection Act 2023. End-to-end encrypted telemetry and explicit family consent controls.',
    keyMetric: 'AES-256 On-Device Vault',
    targetSectionId: 'section-security',
    position: [-1.4, -0.6, 3.6],
    orbitRadius: 3.8,
    angle: 320,
  },
];
