import { SpatialZoneConfig } from './types';

export const SPATIAL_ZONES: SpatialZoneConfig[] = [
  {
    id: 'zone-cognitive',
    name: 'Cognitive Games',
    category: 'cognitive',
    emoji: '🧠',
    color: '#19C3B1',
    accentColor: '#38D9C5',
    glowColor: 'rgba(25, 195, 177, 0.4)',
    tagline: 'Culturally Rooted Engagement',
    shortDesc: 'Adaptive memory matching, attention tasks, recognition, and speed exercises.',
    fullDesc: 'Interactive activities calibrated across 6 cognitive domains including short-term recall, attention endurance, pattern recognition, and familiar sound identification.',
    keyMetric: '6 Calibrated Domains',
    targetSectionId: 'section-cognitive-games',
    position: [0, 1.2, 4.0],
    orbitRadius: 4.0,
    angle: 0,
  },
  {
    id: 'zone-routine',
    name: 'Daily Routine',
    category: 'routine',
    emoji: '💊',
    color: '#F4B740',
    accentColor: '#F59E0B',
    glowColor: 'rgba(244, 183, 64, 0.4)',
    tagline: 'Predictable Circadian Structure',
    shortDesc: 'Structured daily timeline for medication reminders, meals, hydration, and restful pacing.',
    fullDesc: 'Paced daily schedule with morning medication checks, hydration tracking, midday cognitive exercise, and evening calming routines to ease sundowning.',
    keyMetric: 'Morning • Midday • Evening',
    targetSectionId: 'section-daily-routine',
    position: [3.5, 0.8, 2.0],
    orbitRadius: 4.0,
    angle: 60,
  },
  {
    id: 'zone-family',
    name: 'Family Connect',
    category: 'family',
    emoji: '❤️',
    color: '#FF5C6C',
    accentColor: '#F87171',
    glowColor: 'rgba(255, 92, 108, 0.4)',
    tagline: 'Warm Family Communication',
    shortDesc: 'Shared photos, messages, voice notes, and loving video communication.',
    fullDesc: 'Connects elders with family members living across cities with single-tap photo calling, asynchronous voice love notes, and reassuring activity updates.',
    keyMetric: 'Instant Voice & Photos',
    targetSectionId: 'section-family-connect',
    position: [3.5, -0.6, -2.0],
    orbitRadius: 4.0,
    angle: 120,
  },
  {
    id: 'zone-sounds',
    name: 'Peaceful Sounds',
    category: 'sounds',
    emoji: '🎵',
    color: '#5BA7FF',
    accentColor: '#60A5FA',
    glowColor: 'rgba(91, 167, 255, 0.4)',
    tagline: 'Brahmaputra Natural Soundscapes',
    shortDesc: 'Gentle water movement, ambient nature sounds, and soothing melodies.',
    fullDesc: 'Immersive regional audio therapy inspired by the Brahmaputra river, monsoon rain in Sohra, tea garden pine breeze, and calming acoustic music for relaxation.',
    keyMetric: 'Calming Soundscapes',
    targetSectionId: 'section-peaceful-sounds',
    position: [0, -1.2, -4.0],
    orbitRadius: 4.0,
    angle: 180,
  },
  {
    id: 'zone-progress',
    name: 'Cognitive Progress',
    category: 'progress',
    emoji: '📊',
    color: '#38D9C5',
    accentColor: '#2DD4BF',
    glowColor: 'rgba(56, 217, 197, 0.4)',
    tagline: 'Healthcare Analytics Trends',
    shortDesc: 'Activity completion, memory trends, attention span, and engagement consistency.',
    fullDesc: 'Objective longitudinal activity tracking with 7, 14, and 30-day trendlines that give caregivers and clinicians clear visibility into daily cognitive engagement.',
    keyMetric: '7 / 14 / 30-Day Trends',
    targetSectionId: 'section-cognitive-progress',
    position: [-3.5, -0.6, -2.0],
    orbitRadius: 4.0,
    angle: 240,
  },
  {
    id: 'zone-careteam',
    name: 'Care Team',
    category: 'careteam',
    emoji: '👩‍⚕️',
    color: '#35D07F',
    accentColor: '#10B981',
    glowColor: 'rgba(53, 208, 127, 0.4)',
    tagline: 'Caregiver & Clinician Circle',
    shortDesc: 'Dedicated caregiver summaries, clinical notes, alerts, and remote reassurance.',
    fullDesc: 'Synchronized workspace allowing family caregivers and medical officers to review activity overview, routine adherence, and patient notes collaboratively.',
    keyMetric: 'Family & Doctor Circle',
    targetSectionId: 'section-caregiver',
    position: [-3.5, 0.8, 2.0],
    orbitRadius: 4.0,
    angle: 300,
  },
];

